### ISSUE TITLE
not good with VS

### ISSUE THREAD

**Issue by rmpitts94** [BrianLima/UWPHook#79]
so i am having difficulty with this as i have never done anything with visual studio. many other programs but not this. SO i just downloaded it. clone the GIT, insert the two DLL files as reference press start and first it says

"there were dome build errors. Would you like to continue and run the last successful build."

Have to press yes otherwise nothing happens. So i press yes and it errors out with:

"Visual Studio cannot start debugging because the debug target 'C:\users\USERNAME\ source\repos\UWPHook\bin\Debug\UQPHook\Bin\Debug\UWPHook.exe' is missing. "("username" is just a filler) "Please build the project and rety, or set the OutputPath and AssembyName preperties appropriately to the point at the correct location for the target Assembly."

Here is the Output:

Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MaterialDesignThemes.4.1.0\build\MaterialDesignThemes.targets.	
UWPHook	C:\Users\rober\source\repos\UWPHook\UWPHook\UWPHook.csproj	225	

Warning		The referenced component 'Crc32.NET' could not be found.	UWPHook			
Warning		The referenced component 'Newtonsoft.Json' could not be found.	UWPHook			
Warning		The referenced component 'System.Xml.Linq' could not be found.	UWPHook			
Warning		The referenced component 'MaterialDesignThemes.Wpf' could not be found.	UWPHook			
Warning		The referenced component 'Microsoft.CSharp' could not be found.	UWPHook			
Warning		The referenced component 'System.Xml' could not be found.	UWPHook			
Warning		The referenced component 'VDFParser' could not be found.	UWPHook			
Warning		The referenced component 'System.Management.Automation' could not be found.	UWPHook			
Warning		The referenced component 'System' could not be found.	UWPHook			
Warning		The referenced component 'MaterialDesignColors' could not be found.	UWPHook			
Warning		The referenced component 'WindowsBase' could not be found.	UWPHook			
Warning		The referenced component 'System.Net.Http' could not be found.	UWPHook			
Warning		The referenced component 'System.Drawing' could not be found.	UWPHook			
Warning		The referenced component 'SharpSteam' could not be found.	UWPHook			
Warning		The referenced component 'System.Data.DataSetExtensions' could not be found.	UWPHook			
Warning		The referenced component 'IWshRuntimeLibrary' could not be found.	UWPHook			
Warning		The referenced component 'System.Core' could not be found.	UWPHook			
Warning		The referenced component 'System.Net.Http.Formatting' could not be found.	UWPHook			
Warning		The referenced component 'PresentationFramework' could not be found.	UWPHook			
Warning		The referenced component 'PresentationCore' could not be found.	UWPHook			
Warning		The referenced component 'System.Xaml' could not be found.	UWPHook			
Warning		The referenced component 'System.Data' could not be found.	UWPHook			

Now i assume my lack of knowledge of this program is my issue. but if i could recieve some help id greatly appreciate it. Changed a game from xbox to pc and its the only way to allow cross platform saves. Thanks for any help.

**Comment by BrianLima** [comment]
Hi, i'm not sure of what is the problem you have since it is not clear if you are trying to code in this project or if you just want to use UWPHook to create shortcuts in your Steam, but first things first:

-  If you want to develop, you need to restore the nugget packages needed by the project, for that you may follow [this documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore), then you will be able to build the project. [This video](https://www.youtube.com/watch?v=Eb9LW4DaFFQ) goes around the basics of compiling a C# project and might be of some help.
- If you only want to use UWPHook, you only need to download the latest executable from the [releases tab](https://github.com/BrianLima/UWPHook/releases), you can try either [the installer(preferred)](https://github.com/BrianLima/UWPHook/releases/download/2.10.0/UWPHook.exe), or the [zip/portable executable](https://github.com/BrianLima/UWPHook/releases/download/2.10.0/UWPHook.zip)

Also, UWPHook does not enable cross platform saves, that is a feature from Microsoft and their `Play anywhere` program, and depends on a game by game basis, Halo, Gears, Forza and most first party Xbox Studios titles are cross save, but Wreckfest, Deep Rock, Dead Cells and most other third party games are not

**Comment by IdiosApps** [comment]
FWIW I was able to get running with Visual Studio fairly easily:

- add .dlls to C:\Windows\SysWOW64
- restart PC
- clone the repo
- open folder with Visual Studio, double click on .sln solution
- Right click references -> Browse -> Browse -> C:\Windows\SysWOW64/abc.dll, for both .dlls
- Select `defaultBuild`and start

![image](https://github.com/BrianLima/UWPHook/assets/12559216/3ea0df2c-1fd8-4575-975c-80ba58232d87)

I just had to Google the .dll stuff :)
