### ISSUE TITLE
Icons randomly disappear after a bit

### ISSUE THREAD

**Issue by HannahBanana1312** [BrianLima/UWPHook#90]
Games will lose their icon in Steam randomly, only way I can find to fix it is to download an icon file manually from steamgriddb.com or re-import the game with UWPHook
![image](https://user-images.githubusercontent.com/36461227/180920219-46d480fb-1452-4a08-81a3-980469663c83.png)

**Comment by KyleStilkey** [comment]
This happens when a game updates. My currently solution right now is to create a image folder inside of my steam install and if a game updates just put a image icon in the folder and change it to this version as the file will always remain here. What happens with most games that update through the Store/Xbox App is the folder/files change location so the original file that was being used no longer exists and you get this issue.

**Comment by BrianLima** [comment]
Hi @HannahBanana1312 , @KyleStilkey the new release fixes this issue, could you maybe give it a go?

https://github.com/BrianLima/UWPHook/releases/tag/2.11.0

**Comment by KyleStilkey** [comment]
@BrianLima I will let you know if any issues comes up with the new implementation but it sounds like you have fixed this. 👍

**Comment by KyleStilkey** [comment]
Looks like things are good, I will reopen if I notice it happening again but thank you for the fix!
